---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://grafana.github.io/helm-charts
      chart: promtail
      version: 3.7.0
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: grafana/promtail
      version: 2.3.0
    extraPorts:
      syslog:
      name: tcp-syslog
      containerPort: 1514
      protocol: TCP
      service:
      type: LoadBalancer
      port: 1514
      externalIPs:
        - ${SVC_LOKI_IP}
      externalTrafficPolicy: Local
    config:
      lokiAddress: http://loki:3100/loki/api/v1/push
      snippets:
        extraScrapeConfigs: |
          - job_name: syslog
            syslog:
              listen_address: 0.0.0.0:1514
              labels:
                job: syslog
