---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-config
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
