---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: home-assistant
      version: 11.2.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    useHostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    image:
      repository: homeassistant/home-assistant
      tag: 2021.12.4
    env:
      TZ: "Europe/Belgrade"
    service:
      main:
        type: LoadBalancer
        externalIPs:
          - "${SVC_HASS_IP}"
        externalTrafficPolicy: Local
        ports:
          http:
            port: 8123
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
          nginx.org/websocket-services: home-assistant
        hosts:
          - host: "hass.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "hass.${SECRET_DOMAIN}"
    postgresql:
      enabled: true
      postgresqlUsername: home-assistant
      postgresqlPassword: home-assistant-pass
      postgresqlDatabase: home-assistant
      persistence:
        enabled: true
        existingClaim: hass-psql
    podSecurityContext:
      supplementalGroups:
        - 100
    persistence:
      config:
        enabled: true
        existingClaim: hass-config
