---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rtorrent
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: rtorrent-flood
      version: 8.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: jesec/rtorrent-flood
      tag: latest@sha256:f0c894ec459e52d85bc69685247ddbd8e8fcf3709b50bf8ee8b0df3bf69b7b49
    env:
      TZ: "Europe/Belgrade"
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
        hosts:
          - host: "rtorrent.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "rtorrent.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: false
        existingClaim: rtorrent-config
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: 10.5.0.10
            path: /mnt/user/Multimedia
        mountPath: /multimedia
    config: |
      session.use_lock.set = no
      method.insert = cfg.basedir,  private|const|string, (cat,(fs.homedir),"/.local/share/rtorrent/")
      method.insert = cfg.download, private|const|string, (cat,"/downloads/","download/")
      method.insert = cfg.logs,     private|const|string, (cat,(cfg.download),"log/")
      method.insert = cfg.logfile,  private|const|string, (cat,(cfg.logs),"rtorrent-",(system.time),".log")
      method.insert = cfg.session,  private|const|string, (cat,(cfg.basedir),".session/")
      method.insert = cfg.watch,    private|const|string, (cat,(cfg.download),"watch/")
      fs.mkdir.recursive = (cat,(cfg.basedir))
      fs.mkdir = (cat,(cfg.download))
      fs.mkdir = (cat,(cfg.logs))
      fs.mkdir = (cat,(cfg.session))
      fs.mkdir = (cat,(cfg.watch))
      fs.mkdir = (cat,(cfg.watch),"/load")
      fs.mkdir = (cat,(cfg.watch),"/start")
      schedule2 = watch_load, 11, 10, ((load.verbose, (cat, (cfg.watch), "load/*.torrent")))
      schedule2 = watch_start, 10, 10, ((load.start_verbose, (cat, (cfg.watch), "start/*.torrent")))
      dht.add_bootstrap = dht.transmissionbt.com:6881
      dht.add_bootstrap = dht.libtorrent.org:25401
      throttle.max_uploads.set = 100
      throttle.max_uploads.global.set = 250
      throttle.min_peers.normal.set = 20
      throttle.max_peers.normal.set = 60
      throttle.min_peers.seed.set = 30
      throttle.max_peers.seed.set = 80
      trackers.numwant.set = 80
      network.port_range.set = 6881-6881
      network.max_open_files.set = 600
      network.max_open_sockets.set = 300
      pieces.memory.max.set = 1800M
      session.path.set = (cat, (cfg.session))
      directory.default.set = (cat, (cfg.download))
      log.execute = (cat, (cfg.logs), "execute.log")
      encoding.add = utf8
      system.daemon.set = true
      system.umask.set = 0002
      system.cwd.set = (directory.default)
      network.http.max_open.set = 50
      network.http.dns_cache_timeout.set = 25
      network.scgi.open_local = (cat,(cfg.basedir),rtorrent.sock)
      print = (cat, "Logging to ", (cfg.logfile))
      log.open_file = "log", (cfg.logfile)
      log.add_output = "info", "log"
