---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: 10.5.0.220-10.5.0.240
  INGRESS_NGINX_LB: 10.5.0.220
  SVC_PLEX_IP: 10.5.0.221
  SVC_HASS_IP: 10.5.0.222
  SVC_MQTT_IP: 10.5.0.223
  SVC_PIHOLE_IP: 10.5.0.224
  SVC_UNBOUND_IP: 10.5.0.225
  SVC_QBIT_IP: 10.5.0.226
