# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:rP882jWLtTUHwDIX,iv:3URyZUhpXY/dVY+9GI8a6kFDo25lwl+GNYv0rIA2img=,tag:YibzPVGaPMSP3gRAyKLbUw==,type:str]
  SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:6Nem3de6GnBN/tnMi6xZE1myDw==,iv:ebN4GSKT42FihNWlDe8eixXRsx5fLU9VcVJom41tkaQ=,tag:m1UZs2EMZ6v3bFMednNX3w==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2021-08-05T13:18:32Z"
  mac: ENC[AES256_GCM,data:hNO0QSLs+867dsDVAJ5c4zZqZxV61grj4e6Z8LD9Z0MTkDMp6IwZOkGQpgKDPzCQGSS0mx9nPtpb6N+HtqlCLYregFZFDcrlAKU1HdLqHFIvv6g9PDqvBhmNyADbtDtM8eUhg3A1353BLWq470uVyfK+b0olaTSAJj/jDjG5//0=,iv:W8ITPHFCtcaxIhNhSsp8dofuvYcsUmi0WVGV814zZpQ=,tag:oSX5p5UKuL3XieyhK8qjYg==,type:str]
  pgp:
    - created_at: "2021-08-05T13:18:30Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        wcFMA5GTmVykevH4ARAAbPxTjl4q5u6w2o1N7gWN7xApNhUFNS/A4Lc835YtHrHd
        cxBxJvAEAWxJ/6I2aZKNywbvPqP1R2sx1sjBsEZnsXgUyF1Ur8qqphSJCCb7JvPl
        AAlrHVi39u/QW2VSH3OL3IUtjKN865PqOjOcSqzY570+GCv/+ddK1SBBDnBMaF+J
        7mymnrJUAEEb9WllbSuyTXBtnts//wFrUAzSyDCH2LW2oIWehz5F68DpMWGf9RLx
        aGfR7SjotMjm6VDw/ZuurAAZ1Pk8+HKJNIgipC2FjG6qggtZQhR5zQFh1p/d//vn
        iqIar3H14OJgBwgxj/WIfscILjg9s6s2CWILs+j0iXNsyS5Fk47ExbT4CfSDY6tX
        O65GrtLPNZsUhTTBkonCMQQTdj5l09XIRrJKMBM0E/2uohxZh4ZgctJ0pY3/9Q0F
        +NQE0LZZUp5ndyXpBaRiVbntziS89if3AmU82b10jNE8p3WUUFYxPhg7F+IFRqTi
        j1Q2ghZ5fU7VfqblLIsTELQ3LN3EDFwEpEXPt+uRMlm6lmXrDS8AXz6UnQAl7AzG
        uJukOJY7KC7Af5a15LY7QgMZ0Swfpyns3zU6cFUXAN73KN69fg7vqcWVToAyh670
        I6sEs/SZPbiBeWktpjoeDN23MeiKI0QGNHxyoFQwAmXeGiT0PPp+7RCvehIXp2vS
        5gHz6FBCzLuOxnW4F+um8gSy5VBawTtroOPvovbuCRpQoQx4eG6Z0Nmoj0rt+JN8
        BF1j+Rc05A4JxYPgVVsmszvk6ePz5dHiFaUGvvu1FNpNG+Ju168nAA==
        =jwEw
        -----END PGP MESSAGE-----
      fp: E7758C1D6AFE6A2985324E2A3B53C8DDDC1C9E3E
    - created_at: "2021-08-05T13:18:30Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        wcFMAxLLGwPem12nARAAbC1ahyI1X0vBe3zCUymJMsU1sWL9rZZafW2o+dGtpA7t
        FPTuojZgJ63sEC0lQJQLVfaU/O+gRuoz0GkuAzSm/f65c2a0kN6yrwLs3qf9SqYw
        e7aiUh/+zZY3e16cIMLzqQ0bW4AXKa91/Owg83jL0ZPv3yeqdm9THUniYsRxfZc0
        rGipGaTJc0K7NVjIbLBbLhG59vjIfkhWeik5hUfCf7gad5bqFtrejQDpio+FW2N8
        OmbD6NDgvdSirROFzNv42GxHtogLcOV+twG4MJJ0GAgl+Svug/zrGeVR+Azwwy6U
        r94CVkdi/0Oe0hTecDIYtccIJOZF9pypB8YjzygO1s1t6ob0rS2oX+D1hjMfTIFH
        5rhG56bchPoNNZ8SYL5F112akMMjoFdxpyz4LAB4zlwD/t0vlyF8uhCGgfOe3RYy
        YLUOPcYl2gv73QMiWntYWnrY+48RfWj/PTZLO9uHwPp1ywgTpOEpRiC/2/73l8TY
        qgCyY+ooBOP6Lncc3X5Ouchc/7K6t0K5eQU0jBs7gd9PPOqjc2Xo3Ru+gGNBAcdb
        V+ux3NzhBTjfo8ujFtMgn0bGLfeClST08zXjMJBCLbbGkNy/OruaDQY7kk2iNiyV
        4ewjjSJavI5Q2pZ+9VKVd5cQDFH5T1TREiRhXOVZKHModj4nD7DsbIbbivMVPu7S
        5gER+Pi4E4OPtSaFCVJnNrngxoA5Xunb3isNNRxAO67rKlpHYnDDwyYjvDVGTqxn
        5xf6yWfC3NOFCDH1u+muIPHk2QAD/0f9QfcuHoui1xmN5+LPT5DIAA==
        =wG3O
        -----END PGP MESSAGE-----
      fp: 94B768FB2758DFBF5CF7621933E4CADC5E1E4F06
  encrypted_regex: ^(data|stringData)$
  version: 3.7.1
